# Generated by Django 2.1.7 on 2019-03-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '__first__'),
        ('twitteruser', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitteruser.TwitterUser', verbose_name='Tagged User')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet', verbose_name='Tweet')),
            ],
        ),
    ]
