# Generated by Django 2.1.7 on 2019-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='email',
            field=models.EmailField(default='jacobrichardjohnson94@gmail.com', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, to='twitteruser.TwitterUser', verbose_name='Followers'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='handle',
            field=models.CharField(max_length=18, unique=True, verbose_name='Twitter Handle'),
        ),
    ]
