# Generated by Django 2.1.7 on 2019-03-15 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20190315_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
    ]
