# Generated by Django 2.1.7 on 2019-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_auto_20190315_1800'),
        ('tweet', '0005_auto_20190317_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='twitteruser.TwitterUser', verbose_name='Favorites'),
        ),
    ]
